/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Action,  DishwasherUpdate,  DryerUpdate,  LightsResult,  OvenUpdate,  ThermostatUpdate,  WasherUpdate } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface DishwasherUpdate {
        result?: ("turn_off" | "do_nothing" | null)
    }
    
    export interface DryerUpdate {
        result?: ("turn_off" | "do_nothing" | null)
    }
    
    export interface LightsResult {
        location?: (string | null)
        name?: (string | null)
        isOn?: (boolean | null)
    }
    
    export interface OvenUpdate {
        result?: ("update" | "turn_off" | "share_info" | "do_nothing" | null)
        targetTemperature: ((number | null) | null)
    }
    
    export interface ThermostatUpdate {
        result?: ("update" | "turn_off" | "share_info" | "do_nothing" | null)
        mode: (("heat" | "cool" | null) | null)
        targetTemperature: ((number | null) | null)
        currentTemperature: ((number | null) | null)
    }
    
    export interface WasherUpdate {
        result?: ("turn_off" | "share_info" | "do_nothing" | null)
    }
    
}