/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {Action, DishwasherUpdate, DryerUpdate, LightsResult, OvenUpdate, ThermostatUpdate, WasherUpdate} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  env?: Record<string, string | undefined>
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ActionClassifier(
      query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ActionClassifier",
        {
          "query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleDishwasher(
      dishwasher: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleDishwasher",
        {
          "dishwasher": dishwasher,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleDryer(
      dryer: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleDryer",
        {
          "dryer": dryer,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleLights(
      lights: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleLights",
        {
          "lights": lights,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleOven(
      oven: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleOven",
        {
          "oven": oven,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleThermostat(
      thermostat: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleThermostat",
        {
          "thermostat": thermostat,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleWasher(
      washer: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleWasher",
        {
          "washer": washer,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ActionClassifier(
      query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ActionClassifier",
        {
          "query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleDishwasher(
      dishwasher: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleDishwasher",
        {
          "dishwasher": dishwasher,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleDryer(
      dryer: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleDryer",
        {
          "dryer": dryer,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleLights(
      lights: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleLights",
        {
          "lights": lights,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleOven(
      oven: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleOven",
        {
          "oven": oven,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleThermostat(
      thermostat: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleThermostat",
        {
          "thermostat": thermostat,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HandleWasher(
      washer: string,query: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "HandleWasher",
        {
          "washer": washer,"query": query
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}