/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    DishwasherUpdate: ClassViewer<'DishwasherUpdate', "result">;
    
    DryerUpdate: ClassViewer<'DryerUpdate', "result">;
    
    LightsResult: ClassViewer<'LightsResult', "location" | "name" | "isOn">;
    
    OvenUpdate: ClassViewer<'OvenUpdate', "result" | "targetTemperature">;
    
    ThermostatUpdate: ClassViewer<'ThermostatUpdate', "result" | "mode" | "targetTemperature" | "currentTemperature">;
    
    WasherUpdate: ClassViewer<'WasherUpdate', "result">;
    
    
    Action: EnumViewer<'Action', "LIGHTS" | "DISH" | "OVEN" | "WASHER" | "DRYER" | "THERMOSTAT" | "UNKNOWN">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "DishwasherUpdate","DryerUpdate","LightsResult","OvenUpdate","ThermostatUpdate","WasherUpdate",
          ]),
          enums: new Set([
            "Action",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.DishwasherUpdate = this.tb.classViewer("DishwasherUpdate", [
          "result",
        ]);
        
        this.DryerUpdate = this.tb.classViewer("DryerUpdate", [
          "result",
        ]);
        
        this.LightsResult = this.tb.classViewer("LightsResult", [
          "location","name","isOn",
        ]);
        
        this.OvenUpdate = this.tb.classViewer("OvenUpdate", [
          "result","targetTemperature",
        ]);
        
        this.ThermostatUpdate = this.tb.classViewer("ThermostatUpdate", [
          "result","mode","targetTemperature","currentTemperature",
        ]);
        
        this.WasherUpdate = this.tb.classViewer("WasherUpdate", [
          "result",
        ]);
        
        
        this.Action = this.tb.enumViewer("Action", [
          "LIGHTS","DISH","OVEN","WASHER","DRYER","THERMOSTAT","UNKNOWN",
        ]);
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}